version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: django_web
    volumes:
      - .:/opt/services/generative_AIs_boilerplate/core/src
    ports:
      - 8000:8080
    env_file:
      - ./.environment/.env
    depends_on:
      - redis
      - postgres1

  postgres1:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres1
      - POSTGRES_USER=postgres_role
      - POSTGRES_PASSWORD=postgres_Pass

  redis:
    image: redis:alpine

  celery:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: celery_worker
    command: /celery_worker_starter.sh
    volumes:
      - .:/opt/services/generative_AIs_boilerplate/core/src
    ports:
      - "8010:8010"
    env_file:
      - ./.environment/.env
    depends_on:
      - postgres1
      - redis

volumes:
  postgres_data: